language: scala
scala:
    - 2.11.8

jdk:
    - oraclejdk8

script:
    - ./run_tests.sh

branches:
    only:
        - master
        - 2.1.x
        - 2.0.x
        - dev
    except:
        - maven-repo
